#DISCMARK = ""
#GAMENAME = "朱比华的雾中迷宫"
#GAMEVERSION = "SpicaMaze Ver.1.0.0"
#MANUAL_PATH = ""
#SCREEN_SIZE = 1280, 800
#START_SCENE = "maze"
#MENU_SCENE = "maze", 0
#CANCEL_SCENE = "maze", 0
#CONFIG.WINDOW_MODE = 0
#CONFIG.VOLUME.ALL = 210
#CONFIG.VOLUME.BGM = 105
#CONFIG.VOLUME.PCM = 155
#CONFIG.VOLUME.SE = 150
#CONFIG.BGMFADE_ONOFF = 0
#CONFIG.FONT.TYPE = 3
#CONFIG.FONT.NAME = "Microsoft YaHei"
#CONFIG.FONT.FUTOKU = 0
#CONFIG.FONT.SHADOW = 0
#MOUSE_CURSOR.CNT = 1
#MOUSE_CURSOR.000.FILE = "sm_cursor"
#MOUSE_CURSOR.DEFAULT = 0
#JOYPAD.ALLOW_JOYPAD_MODE = 1
#JOYPAD.DPAD_CONTROL_MODE = 2
#JOYPAD.LEFT_STICK_CONTROL_MODE = 2
#JOYPAD.SHORTCUT.CNT = 0
#SYSCOMMENU.READ_SKIP = 0, 0, ""
#SYSCOMMENU.UNREAD_SKIP = 0, 0, ""
#SYSCOMMENU.AUTO_SKIP = 0, 0, ""
#SYSCOMMENU.AUTO_MODE = 0, 0, ""
#SYSCOMMENU.HIDE_MWND = 0, 0, ""
#SYSCOMMENU.SAVE = 0, 0, ""
#SYSCOMMENU.LOAD = 0, 0, ""
#SYSCOMMENU.RETURN_SEL = 0, 0, ""
#SYSCOMMENU.CONFIG = 0, 0, ""
#SYSCOMMENU.MANUAL = 0, 0, ""
#SYSCOMMENU.VERSION = 1, 1, "版本"
#SYSCOMMENU.RETURN_MENU = 0, 0, ""
#SYSCOMMENU.GAME_END = 1, 1, "退出游戏"
#SYSCOMMENU.CANCEL = 1, 1, "返回"
#SAVE.CNT = 1
#QUICK_SAVE.CNT = 0
#END_SAVE.CNT = 0
#SAVE_THUMB.USE = 0
#FLAG.CNT = 256
#GLOBAL_FLAG.CNT = 64
#CALL_FLAG.CNT = 64
#DATABASE.CNT = 0
#COLOR_TABLE.CNT = 256
#COLOR_TABLE.000 = 38, 59, 58
#COLOR_TABLE.001 = 250, 247, 235
#COUNTER.CNT = 4
#WORLD.CNT = 1
#OBJECT.CNT = 800
#OBJECT.000-799.USE = 1
#OBJECT.000-799.SAVE = 0
#OBJBTNGROUP.CNT = 1
#MWND.CNT = 1
#MWND.000.MOJI_CNT = 20, 4
#MWND.000.MOJI_SIZE = 24
#MWND.000.MESSAGE_POS = 24, 24
#MWND.000.WINDOW_POS = 0, 700
#MWND.000.WINDOW_SIZE = 640, 200
#MWND.000.WAKU_NO = -1
#FRAME_ACTION_CH.CNT = 4
#EFFECT.CNT = 1
#SHAKE.CNT = 0
#QUAKE.CNT = 0
#EDITBOX.CNT = 0
#FONT_FILE.CNT = 0
#BGM.CNT = 1
#BGM.000 = "sm_music", "sm_music", 0, -1, 0
#PCMCH.CNT = 4
#PCMEVENT.CNT = 4
#SE.CNT = 8
#G00BUF.CNT = 32
#FLICK_SCENE.CNT = 0
